misc: Copy .github directory from develop to stable (#458)
This is done periodically as the Github Action's infrastructure reads
files from the repos main branch (`stable`) where as changes are made to
`develop`'s ".github" which should be made live ASAP.

This does not affect the gem5 build or any configuration scripts, only
how testing is performed via GitHub and other info used by Github (e.g.,
".github/ISSUE_TEMPLATE" which outlines the templates for creating
issues via our GitHub issues page.

diff --git a/.github/workflows/weekly-tests.yaml b/.github/workflows/weekly-tests.yaml
--- a/.github/workflows/weekly-tests.yaml
+++ b/.github/workflows/weekly-tests.yaml
@@ -13,7 +13,11 @@ on:
 jobs:
     build-gem5:
         runs-on: [self-hosted, linux, x64]
+<<<<<<< HEAD
         container: ghcr.io/gem5/ubuntu-22.04_all-dependencies:latest
+=======
+        container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
+>>>>>>> misc: Copy .github directory from develop to stable (#458)
         outputs:
             build-name: ${{ steps.artifact-name.outputs.name }}
         steps:
@@ -36,13 +40,20 @@ jobs:
 
   # start running the very-long tests
 <<<<<<< HEAD
+<<<<<<< HEAD
+=======
+>>>>>>> misc: Copy .github directory from develop to stable (#458)
     testlib-very-long-tests:
         strategy:
             fail-fast: false
             matrix:
                 test-type: [gem5_library_example_tests, gem5_resources, parsec_benchmarks, x86_boot_tests]
         runs-on: [self-hosted, linux, x64]
+<<<<<<< HEAD
         container: ghcr.io/gem5/ubuntu-22.04_all-dependencies:latest
+=======
+        container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
+>>>>>>> misc: Copy .github directory from develop to stable (#458)
         needs: [build-gem5]
         timeout-minutes: 4320 # 3 days
         steps:
@@ -50,6 +61,7 @@ jobs:
               run: rm -rf ./* || true rm -rf ./.??* || true rm -rf ~/.cache || true
             - uses: actions/checkout@v3
               with:
+<<<<<<< HEAD
         # Scheduled workflows run on the default branch by default. We
         # therefore need to explicitly checkout the develop branch.
 <<<<<<< HEAD
@@ -205,31 +217,60 @@ jobs:
 <<<<<<< HEAD
 >>>>>>> misc: Add ".github" changes to minor release
 =======
+=======
+        # Scheduled workflows run on the default branch by default. We
+        # therefore need to explicitly checkout the develop branch.
+                  ref: develop
+            - uses: actions/download-artifact@v3
+              with:
+                  name: ${{needs.build-gem5.outputs.build-name}}
+                  path: build/ALL
+            - run: chmod u+x build/ALL/gem5.opt
+            - name: very-long ${{ matrix.test-type }}
+              working-directory: ${{ github.workspace }}/tests
+              run: ./main.py run gem5/${{ matrix.test-type }} --length very-long --skip-build -vv -t $(nproc)
+            - name: create zip of results
+              if: success() || failure()
+              run: |
+                  apt-get -y install zip
+                  zip -r output.zip tests/testing-results
+            - name: upload zip
+              if: success() || failure()
+              uses: actions/upload-artifact@v3
+              env:
+                  MY_STEP_VAR: ${{ matrix.test-type }}_COMMIT.${{github.sha}}_RUN.${{github.run_id}}_ATTEMPT.${{github.run_attempt}}
+              with:
+                  name: ${{ env.MY_STEP_VAR }}
+                  path: output.zip
+                  retention-days: 7
+            - run: echo "This job's status is ${{ job.status }}."
+>>>>>>> misc: Copy .github directory from develop to stable (#458)
 
-  dramsys-tests:
-    runs-on: [self-hosted, linux, x64, build]
-    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
-    timeout-minutes: 4320 # 3 days
-    steps:
-      - uses: actions/checkout@v3
-        with:
+    dramsys-tests:
+        runs-on: [self-hosted, linux, x64]
+        container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
+        timeout-minutes: 4320 # 3 days
+        steps:
+            - uses: actions/checkout@v3
+              with:
           # Scheduled workflows run on the default branch by default. We
           # therefore need to explicitly checkout the develop branch.
-          ref: develop
+                  ref: develop
 
-      - name: Checkout DRAMSys
-        working-directory: ${{ github.workspace }}/ext/dramsys
-        run: |
-          git clone https://github.com/tukl-msd/DRAMSys DRAMSys
-          cd DRAMSys
-          git checkout -b gem5 09f6dcbb91351e6ee7cadfc7bc8b29d97625db8f
-          git submodule update --init --recursive
+            - name: Checkout DRAMSys
+              working-directory: ${{ github.workspace }}/ext/dramsys
+              run: |
+                  git clone https://github.com/tukl-msd/DRAMSys DRAMSys
+                  cd DRAMSys
+                  git checkout -b gem5 09f6dcbb91351e6ee7cadfc7bc8b29d97625db8f
+                  git submodule update --init --recursive
 
       # gem5 is built separately because it depends on the DRAMSys library
-      - name: Build gem5
-        working-directory: ${{ github.workspace }}
-        run: scons build/ALL/gem5.opt -j $(nproc)
+            - name: Build gem5
+              working-directory: ${{ github.workspace }}
+              run: scons build/ALL/gem5.opt -j $(nproc)
 
+<<<<<<< HEAD
       - name: Run DRAMSys Checks
         working-directory: ${{ github.workspace }}
         run: |
@@ -237,3 +278,23 @@ jobs:
           ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/dramsys-traffic.py
           ./build/ALL/gem5.opt configs/example/dramsys.py
 >>>>>>> misc: Copy .github directory from develop to stable
+=======
+            - name: Run DRAMSys Checks
+              working-directory: ${{ github.workspace }}
+              run: |
+                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/arm-hello-dramsys.py
+                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/dramsys-traffic.py
+                  ./build/ALL/gem5.opt configs/example/dramsys.py
+    weekly-tests:
+        # The dummy job is used to indicate whether the weekly tests have
+        # passed or not. This can be used as status check for pull requests.
+        # I.e., if we want to stop pull requests from being merged if the
+        # weekly tests are failing we can add this job as a required status
+        # check.
+        runs-on: ubuntu-22.04
+        needs:
+            - testlib-very-long-tests
+            - dramsys-tests
+        steps:
+            - run: echo "This weekly tests have passed."
+>>>>>>> misc: Copy .github directory from develop to stable (#458)
